### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by andris155** [OpticFusion1/SlimefunReloaded-ChestTerminal#1]
<img width="842" alt="Annotation 2019-12-27 145320" src="https://user-images.githubusercontent.com/8324198/71519658-c0aedc00-28b8-11ea-8e64-8efc0006fb99.png">

**Comment by OpticFusion1** [comment]
Yeaaaaa, The base plugin & none of the addons are on maven, this will happen.
They're not in a good enough state to be put on maven either

**Comment by andris155** [comment]
How to build without maven? :/

**Comment by OpticFusion1** [comment]
Wellll you wouldn't be able to compile a jar anyways, there's MANY MANY errors that still need fixed
